[View in Colaboratory](https://colab.research.google.com/github/vanchanr/Colab-Notebooks/blob/master/numpy.ipynb)

In [0]:
import numpy as np

In [67]:
#numpy ndarray
data = [[2, 3, 6, 7, 8],
        [4, 89, 87, 67, 7],
        [1, 2, 3, 4, 5]]

data = np.array(data)
print(data)
print(data.shape)
print(np.ones((2, 3)))
print(np.zeros((2, 3), int))

[[ 2  3  6  7  8]
 [ 4 89 87 67  7]
 [ 1  2  3  4  5]]
(3, 5)
[[1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]]


In [68]:
x = np.arange(10)
print(x)
print(x[2:5])
x[5:8] = 0
print(x)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[0 1 2 3 4 0 0 0 8 9]


In [69]:
#Arithmetic operations
A = np.array([[2, 4, 6],
              [3, 6, 9]])
print(A + 5)
print(A - 3)
print(A * A) #Square of every element. Not matrix multiplication
print(10 * A)

[[ 7  9 11]
 [ 8 11 14]]
[[-1  1  3]
 [ 0  3  6]]
[[ 4 16 36]
 [ 9 36 81]]
[[20 40 60]
 [30 60 90]]


In [70]:
#reshape, transpose

A = np.arange(16)
A = A.reshape((4, 4))
print("A=", A)

A_ = A.T
print("A'=", A_)

A= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
A'= [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [71]:
np.random?
R = np.random.randn(2, 3) #normally distributed values with mean=0, variance=1
#same as np.random.standard_normal((2,3))
print(R)

[[ 0.57191585  0.34383057 -0.51841962]
 [-3.13471753 -1.61534098 -1.40314357]]


In [72]:
#statistical methods
data = np.random.randn(10, 10)
print(data.mean())
print(data.min())
print(data.var())

0.14960064508837465
-2.380180476128269
0.9910184373177257


In [73]:
#Matrix class

X = np.arange(10).reshape((2,5))
Y = np.ones((5,2))
print("X=", X)
print("Y=", Y)
#print("X * Y =", X*Y) =>Error

X = np.matrix(X)
Y = np.matrix(Y)
print("X=", X)
print("Y=", Y)
print("X * Y =", X*Y) #Matrix Multiplication

X= [[0 1 2 3 4]
 [5 6 7 8 9]]
Y= [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
X= [[0 1 2 3 4]
 [5 6 7 8 9]]
Y= [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
X * Y = [[10. 10.]
 [35. 35.]]
